/////////////// CONDITIONAL COMPILATION EXAMPLE #3 /////////////////
/* MyHeader.h */

#ifndef _MY_HEADER_		// If _MY_HEADER_ is not defined…
#define _MY_HEADER_		// …then define _MY_HEADER_ and…

extern int npcChoice (int npc);			// …this declaration…
extern int fileOutput(char * name, char * stringResult, int gameNumber);		// …and this one…

#endif				// That is all.